DEFAULT_LGD = 1.0
DATASET_PATH = "data/german_credit_data.csv"
TEST_SIZE = 0.2
RANDOM_STATE = 42
OPPORTUNITY_PROFIT_RATE = 0.15
DECISION_TIE_TOLERANCE = 0.05
REVIEW_COST_GAP_RATIO = 0.1
REVIEW_PROBABILITY_SPREAD = 0.12
